const personas = [
  {
    id: "just-got-medicare",
    name: "Linda Martinez",
    age: 65,
    avatar: "\ud83d\udc69\u200d\ud83e\uddb3",
    tagline: "Just got Medicare, looking for best option",
    description:
      "Uninsured, age 65, just received Medicare card. Looking for the best coverage option. Cost-sensitive.",
    background: {
      insuranceType: "None — currently uninsured",
      employerSize: null,
      workStatus: "Not working, retired",
      hasMedicareCard: true,
      watchedWebinar: true,
      dob: "03/15/1961",
      zip: "85281",
      taxFiling: "Single",
      income: "$38,000",
      premium: "$0/month",
      deductible: "$0",
      oopMax: "$0",
      hasDentalVision: false,
      dentalVisionCost: null,
      dentalAllowance: null,
      visionAllowance: null,
      wantsDentalVision: true,
      dentalVisionImportant: true,
      healthHistory:
        "Generally healthy. Takes lisinopril 10mg for blood pressure. Sees her primary care doctor, Dr. Reyes, at Banner Health in Tempe twice a year. No hospital stays or surgeries in the past 5 years.",
      hitOopMax: false,
      cancerHeartStrokeFamily: false,
      cancerHeartStrokeFamilyDetails: null,
      skilledNursingFamily: false,
      skilledNursingFamilyDetails: null,
    },
    personality:
      'Friendly and cooperative but always asks about price. Will ask "how much is that going to cost me?" at multiple points. Agrees easily once she understands the value. Watched the webinar and has 2-3 questions about what was covered.',
  },
  {
    id: "employer-turning-65",
    name: "Robert Chen",
    age: 64,
    avatar: "\ud83d\udc68\u200d\ud83d\udcbc",
    tagline: "Employer coverage, turning 65 soon",
    description:
      "Currently working with employer health insurance. Turning 65 in 3 months. Wants to compare employer coverage vs Medicare. Worried about penalties.",
    background: {
      insuranceType: "Employer insurance",
      employerSize: "20+ employees",
      workStatus: "Currently working, planning to retire next year",
      hasMedicareCard: false,
      watchedWebinar: true,
      dob: "06/22/1961",
      zip: "90210",
      taxFiling: "Married filing jointly",
      income: "$95,000",
      premium: "$280/month",
      deductible: "$1,500",
      oopMax: "$6,000",
      hasDentalVision: true,
      dentalVisionCost: "$45/month",
      dentalAllowance: "$1,500",
      visionAllowance: "$300",
      wantsDentalVision: true,
      dentalVisionImportant: true,
      healthHistory:
        "Had a knee replacement 2 years ago. Takes atorvastatin 20mg for cholesterol. Sees his orthopedic specialist, Dr. Langston, at Cedars-Sinai quarterly and his primary care doctor, Dr. Park, at UCLA Health once a year. No other major issues.",
      hitOopMax: true,
      hitOopMaxDetails: "Hit OOP max during knee replacement surgery",
      cancerHeartStrokeFamily: true,
      cancerHeartStrokeFamilyDetails:
        "Father had a heart attack at age 72",
      skilledNursingFamily: false,
      skilledNursingFamilyDetails: null,
    },
    personality:
      "Methodical and detail-oriented. Asks good questions. Wants to understand the penalty situation clearly. Will ask about keeping his doctors. Generally trusting but wants all the facts. Watched the webinar with questions about enrollment timeline.",
  },
  {
    id: "ssdi-employer",
    name: "Maria Johnson",
    age: 63,
    avatar: "\ud83d\udc69\u200d\u2695\ufe0f",
    tagline: "On SSDI + employer coverage",
    description:
      "Currently working part-time. On SSDI and employer coverage. Confused about whether Medicare auto-enrollment applies.",
    background: {
      insuranceType: "Employer insurance",
      employerSize: "Fewer than 20 employees",
      workStatus: "Currently working part-time, no retirement plans yet",
      hasMedicareCard: false,
      watchedWebinar: false,
      dob: "11/08/1962",
      zip: "70112",
      taxFiling: "Single",
      income: "$28,000",
      premium: "$120/month",
      deductible: "$2,000",
      oopMax: "$5,000",
      hasDentalVision: false,
      dentalVisionCost: null,
      dentalAllowance: null,
      visionAllowance: null,
      wantsDentalVision: true,
      dentalVisionImportant: true,
      healthHistory:
        "Has fibromyalgia. Takes gabapentin 300mg twice daily for nerve pain and cyclobenzaprine 10mg as needed for muscle spasms. Sees her rheumatologist, Dr. Thibodaux, at Ochsner Health in New Orleans every 3 months. Had a minor outpatient procedure last year. No hospital stays.",
      hitOopMax: false,
      cancerHeartStrokeFamily: true,
      cancerHeartStrokeFamilyDetails:
        "Mother had breast cancer at age 68",
      skilledNursingFamily: false,
      skilledNursingFamilyDetails: null,
    },
    personality:
      "Anxious and confused. Asks a lot of questions, sometimes the same question twice. Needs reassurance. Did NOT watch the webinar. Main concern is SSDI auto-enrollment. Cooperative once she feels understood.",
  },
  {
    id: "skeptical-private",
    name: "James Walker",
    age: 63,
    avatar: "\ud83e\udd28",
    tagline: "Private insurance, skeptical, resistant to ancillary",
    description:
      "Has private individual insurance. Not 65 yet. Skeptical shopper. Needs to understand why Medicare matters. Resistant to ancillary products.",
    background: {
      insuranceType: "Individual insurance (private)",
      employerSize: null,
      workStatus: "Currently working, no plans to retire soon",
      hasMedicareCard: false,
      watchedWebinar: true,
      dob: "09/03/1962",
      zip: "75001",
      taxFiling: "Married filing jointly",
      income: "$72,000",
      premium: "$450/month",
      deductible: "$3,000",
      oopMax: "$8,000",
      hasDentalVision: true,
      dentalVisionCost: "$60/month",
      dentalAllowance: "$1,000",
      visionAllowance: "$250",
      wantsDentalVision: true,
      dentalVisionImportant: true,
      healthHistory:
        "Very healthy. Runs 3 times a week. No medications. Gets an annual physical only. No hospital stays or surgeries in the past 5 years.",
      hitOopMax: false,
      cancerHeartStrokeFamily: false,
      cancerHeartStrokeFamilyDetails: null,
      skilledNursingFamily: false,
      skilledNursingFamilyDetails: null,
    },
    personality:
      'Skeptical and direct. Pushes back on things he does not see the point of. When you bring up cancer/heart/stroke/SNF coverage, says things like "I am healthy, I do not need that" or "that sounds like an upsell." Needs logic not emotion. Respects confidence but challenges weak answers. Watched the webinar but was not fully convinced.',
  },
  {
    id: "free-employer",
    name: "Patricia Davis",
    age: 64,
    avatar: "\ud83d\udc69\u200d\ud83c\udfeb",
    tagline: "Free employer insurance, why switch?",
    description:
      "Has employer insurance and pays nothing for it. Genuinely confused about why she would switch to something that costs money.",
    background: {
      insuranceType: "Employer insurance",
      employerSize: "20+ employees",
      workStatus: "Currently working, retiring in about a year",
      hasMedicareCard: false,
      watchedWebinar: false,
      dob: "01/17/1962",
      zip: "28202",
      taxFiling: "Married filing jointly",
      income: "$68,000",
      premium: "$0/month",
      deductible: "$500",
      oopMax: "$3,000",
      hasDentalVision: true,
      dentalVisionCost: "$0/month",
      dentalAllowance: "$2,000",
      visionAllowance: "$400",
      wantsDentalVision: true,
      dentalVisionImportant: true,
      healthHistory:
        "Had gallbladder removed 3 years ago. Takes levothyroxine 75mcg daily for her thyroid. Otherwise healthy. Sees her primary care doctor, Dr. Okafor, at Atrium Health in Charlotte once a year.",
      hitOopMax: false,
      cancerHeartStrokeFamily: true,
      cancerHeartStrokeFamilyDetails: "Sister had a stroke at age 60",
      skilledNursingFamily: false,
      skilledNursingFamilyDetails: null,
    },
    personality:
      'Friendly but genuinely does not understand why she would pay for something when she currently pays nothing. Will keep coming back to "but I do not pay anything right now." Needs the agent to explain what happens when she retires and loses employer coverage. Did NOT watch the webinar.',
  },
  {
    id: "free-state-subsidized",
    name: "Thomas Green",
    age: 64,
    avatar: "\ud83d\udc74",
    tagline: "Free state-subsidized insurance, why switch?",
    description:
      "On state-subsidized insurance and pays nothing. Wants to know why he should bother with Medicare.",
    background: {
      insuranceType: "State-subsidized insurance",
      employerSize: null,
      workStatus: "Not working, retired",
      hasMedicareCard: false,
      watchedWebinar: true,
      dob: "07/30/1961",
      zip: "89101",
      taxFiling: "Single",
      income: "$22,000",
      premium: "$0/month",
      deductible: "$0",
      oopMax: "$2,000",
      hasDentalVision: true,
      dentalVisionCost: "$0/month",
      dentalAllowance: "$500",
      visionAllowance: "$200",
      wantsDentalVision: true,
      dentalVisionImportant: true,
      healthHistory:
        "Has type 2 diabetes. Takes metformin 1000mg twice daily and lisinopril 20mg for blood pressure. Sees his endocrinologist, Dr. Patel, at Sunrise Health in Las Vegas every 3 months and his primary care doctor, Dr. Coleman, at UMC Health twice a year. No hospital stays in the past 5 years.",
      hitOopMax: false,
      cancerHeartStrokeFamily: true,
      cancerHeartStrokeFamilyDetails:
        "Father died of a heart attack at age 65",
      skilledNursingFamily: true,
      skilledNursingFamilyDetails:
        "Mother spent time in a nursing facility after a fall",
    },
    personality:
      'Quiet and reserved. Gives short answers. Main objection is "I do not pay anything now, why would I switch?" Needs gentle education about what happens at 65 with state-subsidized coverage. Watched the webinar but still has questions. Will open up more when asked about family history — his father\'s death is emotional for him.',
  },
  {
    id: "wants-expertise",
    name: "Barbara Thompson",
    age: 65,
    avatar: "\ud83d\udc69\u200d\u2696\ufe0f",
    tagline: "Wants the best, expects expertise",
    description:
      "Age 65, just got Medicare this month. No coverage in place yet. Wants the best coverage available. Expects confidence and knowledge.",
    background: {
      insuranceType: "None — currently uninsured",
      employerSize: null,
      workStatus: "Not working, retired",
      hasMedicareCard: true,
      watchedWebinar: true,
      dob: "02/28/1961",
      zip: "83702",
      taxFiling: "Single",
      income: "$55,000",
      premium: "$0/month",
      deductible: "$0",
      oopMax: "$0",
      hasDentalVision: false,
      dentalVisionCost: null,
      dentalAllowance: null,
      visionAllowance: null,
      wantsDentalVision: true,
      dentalVisionImportant: true,
      healthHistory:
        "Very healthy. Walks 5 miles a day. No medications. No hospital stays or surgeries. Annual physical only.",
      hitOopMax: false,
      cancerHeartStrokeFamily: false,
      cancerHeartStrokeFamilyDetails: null,
      skilledNursingFamily: false,
      skilledNursingFamilyDetails: null,
    },
    personality:
      'Confident and sharp. Expects YOU to be the expert. If you hesitate or sound unsure, she says things like "Are you sure about that?" or "I thought the webinar said something different." Not mean — just wants to feel she is in good hands. If you sound confident and knowledgeable, she is your best client. Watched the webinar with thoughtful questions.',
  },
  {
    id: "know-it-all",
    name: "Richard Sterling",
    age: 64,
    avatar: "\ud83e\uddd0",
    tagline: "Know-it-all, tries to control the call",
    description:
      "Has private insurance. Turning 65 soon. Acts like he already knows everything. Constantly tries to take over the conversation.",
    background: {
      insuranceType: "Individual insurance (private)",
      employerSize: null,
      workStatus: "Currently working (semi-retired consultant)",
      hasMedicareCard: false,
      watchedWebinar: true,
      dob: "12/05/1961",
      zip: "94102",
      taxFiling: "Married filing jointly",
      income: "$120,000",
      premium: "$550/month",
      deductible: "$2,500",
      oopMax: "$7,500",
      hasDentalVision: true,
      dentalVisionCost: "$75/month",
      dentalAllowance: "$1,500",
      visionAllowance: "$500",
      wantsDentalVision: true,
      dentalVisionImportant: true,
      healthHistory:
        "Healthy. No medications. Had a minor back injury 4 years ago but fully recovered. No hospital stays. Annual physical only.",
      hitOopMax: false,
      cancerHeartStrokeFamily: false,
      cancerHeartStrokeFamilyDetails: null,
      skilledNursingFamily: false,
      skilledNursingFamilyDetails: null,
    },
    personality:
      'Talks a lot. Interrupts. Says "I already know that" and "Let me tell you what I think." Tries to skip ahead. Will challenge you on facts. Key to handling him is politely acknowledging then firmly guiding back to structure. Does not know as much as he thinks — if you catch him on something, he respects you more. Watched the webinar and thinks he understood everything already.',
  },
];

module.exports = personas;
